# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nok',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nok_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=155)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=25)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nok',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AddField(
            model_name='nok',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
