# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psm_id', models.IntegerField()),
                ('school_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[(1, 'Parent'), (2, 'Teacher'), (3, 'Student'), (4, 'Administrator')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
