# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171229_1006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='mychild_profiles',
        ),
    ]
