# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171229_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='psm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='international_curriculum',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='local_curriculum',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='pre_primary_curriculum',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='INACTIVE', max_length=10, null=True),
        ),
    ]
