# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171230_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.CharField(default='all', max_length=155),
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='user_uploads',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='user_comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='user_posts',
        ),
    ]
