# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171230_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
