# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nok',
            name='nok_id',
        ),
    ]
