# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_nok_nok_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('O', 'O Level'), ('A', 'A Level')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('O', 'O Level'), ('A', 'A Level')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='level',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('O', 'O Level'), ('A', 'A Level')], max_length=1, null=True),
        ),
    ]
