# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180107_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsResultsLocalALevelOverall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=8)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('class_teacher_comment', models.TextField()),
                ('house_teacher_comment', models.TextField()),
                ('head_teacher_comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_a_overall',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsLocalALevelSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_a_subject',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsLocalOLevelOverall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('total_marks', models.CharField(max_length=4)),
                ('average_mark', models.CharField(max_length=4)),
                ('aggregate', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.CharField(max_length=3)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_teacher_comment', models.TextField()),
                ('house_teacher_comment', models.TextField()),
                ('head_teacher_comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_o_overall',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsLocalOLevelSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('mark', models.CharField(max_length=6)),
                ('grade', models.CharField(max_length=2)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_o_subject',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsLocalPrimaryOverall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('total_marks', models.CharField(max_length=4)),
                ('average_mark', models.CharField(max_length=4)),
                ('aggregate', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.CharField(max_length=3)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_teacher_comment', models.TextField()),
                ('house_teacher_comment', models.TextField()),
                ('head_teacher_comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_p_overall',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsLocalPrimarySubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_loc_p_subject',
            },
        ),
        migrations.CreateModel(
            name='AcademicsResultsMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('school_class', models.CharField(max_length=15)),
                ('stream', models.CharField(max_length=15)),
                ('type', models.PositiveSmallIntegerField()),
                ('subject_paper', models.CharField(blank=True, max_length=3, null=True)),
                ('mark', models.CharField(max_length=6)),
                ('grade', models.CharField(max_length=2)),
                ('stream_position', models.PositiveIntegerField(blank=True, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'db_table': 'academics_results_marks',
            },
        ),
        migrations.CreateModel(
            name='SchoolSubjectClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compulsory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject')),
                ('subject_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SubjectPaper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academicsresultsmarks',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultsmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultsmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimarysubject',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimarysubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimarysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimaryoverall',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimaryoverall',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalprimaryoverall',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalolevelsubject',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalolevelsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalolevelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocaloleveloverall',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocaloleveloverall',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocaloleveloverall',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalalevelsubject',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalalevelsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalalevelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalaleveloverall',
            name='school_subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalaleveloverall',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='academicsresultslocalaleveloverall',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
    ]
