# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180110_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsresultslocalaleveloverall',
            options={'verbose_name': 'A-level Overall Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultslocalalevelsubject',
            options={'verbose_name': 'A-level Subject Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultslocaloleveloverall',
            options={'verbose_name': 'O-level Overall Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultslocalolevelsubject',
            options={'verbose_name': 'O-level Subject Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultslocalprimaryoverall',
            options={'verbose_name': 'Primary Overall Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultslocalprimarysubject',
            options={'verbose_name': 'Primary Subject Results'},
        ),
        migrations.AlterModelOptions(
            name='academicsresultsmarks',
            options={'verbose_name': 'Student Marks'},
        ),
        migrations.AlterField(
            model_name='academicsresultslocalaleveloverall',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalalevelsubject',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocaloleveloverall',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalolevelsubject',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimaryoverall',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimarysubject',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultsmarks',
            name='school_subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolSubjectClass'),
        ),
    ]
