# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180113_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level_short',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(default='S.1', max_length=20),
        ),
    ]
