# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180116_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(),
        ),
    ]
