# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
