# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nok',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='child_code',
            field=models.CharField(default=32343423, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_news',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nok',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
    ]
