# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180119_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default='user.png', null=True, upload_to='%Y/%m/%d/profile_pics'),
        ),
    ]
