# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'students_and_nok',
            },
        ),
        migrations.AlterField(
            model_name='nok',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default='avatar_default.jpg', null=True, upload_to='%Y/%m/%d/profile_pics'),
        ),
        migrations.AddField(
            model_name='studentnok',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='studentnok',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AddField(
            model_name='studentnok',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
