# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 05:19
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180119_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(default='avatar_default.jpg', upload_to=api.models.student_photo_directory),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
    ]
