# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180120_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsresultslocalaleveloverall',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalaleveloverall',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalalevelsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalalevelsubject',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultslocaloleveloverall',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocaloleveloverall',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalolevelsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalolevelsubject',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimaryoverall',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimaryoverall',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimarysubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimarysubject',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsresultsmarks',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='academicsresultsmarks',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
