# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180120_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsresultslocalaleveloverall',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalaleveloverall',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalaleveloverall',
            name='type',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalalevelsubject',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocaloleveloverall',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocaloleveloverall',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocaloleveloverall',
            name='type',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalolevelsubject',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalprimaryoverall',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalprimaryoverall',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalprimaryoverall',
            name='type',
        ),
        migrations.RemoveField(
            model_name='academicsresultslocalprimarysubject',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='academicsresultsmarks',
            name='stream',
        ),
        migrations.AlterField(
            model_name='academicsresultslocalaleveloverall',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalalevelsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocaloleveloverall',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalolevelsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimaryoverall',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultslocalprimarysubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='academicsresultsmarks',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolClass'),
        ),
    ]
