# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180121_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='school',
            name='psm_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vision',
        ),
        migrations.AddField(
            model_name='school',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolcontactperson',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='international_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='local_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='pre_primary_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolcontactperson',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
