# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180128_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='child_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
