# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180202_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
