# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180202_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='address',
            new_name='physical_address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=False),
        ),
    ]
