# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180204_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
